/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../index';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/common/src/localization';
import * as import4 from '@angular/core/src/di/injector';
import * as import5 from '@angular/core/src/i18n/tokens';
class DndModuleInjector extends import0.NgModuleInjector<import1.DndModule> {
  _CommonModule_0:import2.CommonModule;
  _DndModule_1:import1.DndModule;
  __LOCALE_ID_2:any;
  __NgLocalization_3:import3.NgLocaleLocalization;
  constructor(parent:import4.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _LOCALE_ID_2():any {
    if ((this.__LOCALE_ID_2 == null)) { (this.__LOCALE_ID_2 = 'en-US'); }
    return this.__LOCALE_ID_2;
  }
  get _NgLocalization_3():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_3 == null)) { (this.__NgLocalization_3 = new import3.NgLocaleLocalization(this._LOCALE_ID_2)); }
    return this.__NgLocalization_3;
  }
  createInternal():import1.DndModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._DndModule_1 = new import1.DndModule();
    return this._DndModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.DndModule)) { return this._DndModule_1; }
    if ((token === import5.LOCALE_ID)) { return this._LOCALE_ID_2; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const DndModuleNgFactory:import0.NgModuleFactory<import1.DndModule> = new import0.NgModuleFactory(DndModuleInjector,import1.DndModule);